### ISSUE TITLE
[Bug]: Update 0.25.7 breaks OIDC SSO

### ISSUE THREAD

**Issue by seamon67** [toeverything/AFFiNE#14083]
### What happened?

Looks like this PR 
https://github.com/toeverything/AFFiNE/pull/14061
completely breaks OIDC SSO on self hosted instances.

I am using Authentik.
I updated from 0.25.5 -> 0.25.7 and OIDC SSO no longer works.

I can confirm the OIDC Settings on the Admin WebUI is this
{"args":{"scope":"openid email profile offline_access","claim_id":"preferred_username","claim_name":"name","claim_email":"email"},"issuer":"https://\<URL\>/application/o/affine/","clientId":"\<CLI\>","clientSecret":"\<CLS\>"}

### Distribution version

Linux

### App Version

0.25.7

### Are you self-hosting?

- [x] Yes

### Self-hosting Version

0.25.7

### Relevant log output

```shell
[Nest] 1    WARN [OIDCProvider] <selfhosted:> Failed to verify OIDC id token

and 

[Nest] 1    WARN [OIDCProvider] <selfhosted:> JWSInvalid: Invalid Compact JWS
```

### Anything else?

Logging in using OIDC displays the following error.

Unable to sign in

    Invalid auth state. You might start the auth progress from another device.

**Comment by steffenrapp** [comment]
I'm getting the error message `Invalid OAuth response: Email for this account is not verified.` since the new update. I'm also using Authentik.
I found these links, seems like Authentik sets the `email_verified` claim to `False` by default.
https://docs.goauthentik.io/add-secure-apps/providers/property-mappings/
https://github.com/goauthentik/authentik/issues/16205

**Comment by steffenrapp** [comment]
Now I created a custom property in Authentik with `"email_verified": True`, assigned it to the provider for AFFiNE and now OIDC SSO works again.

**Comment by seamon67** [comment]
> Now I created a custom property in Authentik with `"email_verified": True`, assigned it to the provider for AFFiNE and now OIDC SSO works again.

What are your settings for SSO in the Affine WebUI

**Comment by steffenrapp** [comment]
@seamon67 my settings in the AFFiNE admin panel are the same like yours. I didn't need to change anything here, only in authentik.

**Comment by seamon67** [comment]
I'll try once to see if that fixes it.

**Comment by T00bitob** [comment]
Hi, same issue here. But adding the custom property mapping has not been working for me. 

<img width="1473" height="698" alt="Image" src="https://github.com/user-attachments/assets/7c2fc85d-3ab2-4b4f-a8d7-3eafdb890cf6" />

**Comment by seamon67** [comment]
> Hi, same issue here. But adding the custom property mapping has not been working for me.
> 
> <img alt="Image" width="1473" height="698" src="https://private-user-images.githubusercontent.com/26183442/525379059-7c2fc85d-3ab2-4b4f-a8d7-3eafdb890cf6.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjU0NTc4NjEsIm5iZiI6MTc2NTQ1NzU2MSwicGF0aCI6Ii8yNjE4MzQ0Mi81MjUzNzkwNTktN2MyZmM4NWQtM2FiMi00YjRmLWE4ZDctM2VhZmRiODkwY2Y2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMjExVDEyNTI0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwNzE2MDY1YjM1MmUwNjU3N2ZlNzkyMTRlMTRjYzg5Y2Q4MGYyMTIzOGVkNDAxNmY3YjRjNDA3NzY3OTFiMTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.1S3UUS3WTpdDygn-B33iJN5beLG7TtG51wc9nqgKy9M">

I can't check until later today.
Can you try one thing - Set Encryption Key to '-----------' in the Advanced Protocol Settings.

**Comment by koseduhemak** [comment]
You have to use the custom mapping scope instead of the vanilla "email" scope in your provider config:

<img width="957" height="449" alt="Image" src="https://github.com/user-attachments/assets/6bdf31fe-47a7-4526-a2e9-b2628fa07106" />

Use your custom scope mapping for email attribute (1). 
Deselect the default "email" scope (2).

**Comment by T00bitob** [comment]
I tried setting the encryption key to "------" and deselecting the default email scope. Neither has been working for me, I still get the same error.

<img width="1656" height="1772" alt="Image" src="https://github.com/user-attachments/assets/9c1feffd-d838-415b-8944-336b8e08a11e" />

<img width="1665" height="1553" alt="Image" src="https://github.com/user-attachments/assets/eac0ec58-917d-4ae0-93e1-61bf6b3457fa" />

[Nest] 1  - 12/11/2025, 1:48:35 PM    WARN [OIDCProvider] <selfhosted:http:4a7bd37b-f6ce-49ad-a21c-8b7e2b49abfa> Failed to verify OIDC id token
[Nest] 1  - 12/11/2025, 1:48:35 PM    WARN [OIDCProvider] <selfhosted:http:4a7bd37b-f6ce-49ad-a21c-8b7e2b49abfa> JWKSInvalid: JSON Web Key Set malformed
    at new LocalJWKSet (file:///app/node_modules/jose/dist/webapi/jwks/local.js:33:19)
    at createLocalJWKSet (file:///app/node_modules/jose/dist/webapi/jwks/local.js:108:17)
    at file:///app/node_modules/jose/dist/webapi/jwks/remote.js:131:27
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async RemoteJWKSet.reload (file:///app/node_modules/jose/dist/webapi/jwks/remote.js:143:9)
    at async RemoteJWKSet.getKey (file:///app/node_modules/jose/dist/webapi/jwks/remote.js:110:13)
    at async flattenedVerify (file:///app/node_modules/jose/dist/webapi/jws/flattened/verify.js:73:15)
    at async compactVerify (file:///app/node_modules/jose/dist/webapi/jws/compact/verify.js:15:22)
    at async jwtVerify (file:///app/node_modules/jose/dist/webapi/jwt/verify.js:5:22)
    at async OIDCProvider.verifyIdToken (file:///app/dist/main.js:136786:33) {
  code: 'ERR_JWKS_INVALID'
}

**Comment by seamon67** [comment]
Heh that's the same error I was getting yesterday before doing a Database Revert back to 0.25.5

**Comment by seamon67** [comment]
Alright. I also managed to solve this.

Encryption Key needs to be '---------'. Setting an Encryption Key leads to 'Invalid auth state. You might start the auth progress from another device.'

Next, you need to create a Scope Mapping in the Property Mappings in Authentik.
The 'Scope Name' field is very important. Either name this email or a custom name like 'verified_email'.
Put this in the Expression:
```
return {
    "email": user.email,
    "email_verified": True,
}
```
In Authentik Provider for Affine, make sure this new scope is mapped and the default email scope is removed.

Now in the Affine Admin WebUI, add the new scope if you decided to use a custom name ('verified_email').

It should work now.

**Comment by T00bitob** [comment]
Sorry to bother you about this topic again, but despite changing everything according to your instructions, it still does not work. I would really appreciate it if someone could help me. Thank you!

<img width="842" height="253" alt="Image" src="https://github.com/user-attachments/assets/aab3224b-4782-4074-aa74-e6ef29bf1917" />
<img width="1119" height="538" alt="Image" src="https://github.com/user-attachments/assets/4dd56a9a-67b1-437c-926c-f45e393fa1a9" />
<img width="1112" height="1325" alt="Image" src="https://github.com/user-attachments/assets/4f3024f9-9b97-4187-961f-7013b5fc313c" />
<img width="1116" height="1022" alt="Image" src="https://github.com/user-attachments/assets/dafc77e0-d58c-498b-88d1-9f4b91d1baa9" />

Error I am getting for the affine_server:
```
[Nest] 1  - 12/12/2025, 9:09:34 AM    WARN [OIDCProvider] <selfhosted:http:90ebfc58-b956-4241-8c65-0da2a8b0574f> Failed to verify OIDC id token
[Nest] 1  - 12/12/2025, 9:09:34 AM    WARN [OIDCProvider] <selfhosted:http:90ebfc58-b956-4241-8c65-0da2a8b0574f> JWKSInvalid: JSON Web Key Set malformed
    at new LocalJWKSet (file:///app/node_modules/jose/dist/webapi/jwks/local.js:33:19)
    at createLocalJWKSet (file:///app/node_modules/jose/dist/webapi/jwks/local.js:108:17)
    at file:///app/node_modules/jose/dist/webapi/jwks/remote.js:131:27
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async RemoteJWKSet.reload (file:///app/node_modules/jose/dist/webapi/jwks/remote.js:143:9)
    at async RemoteJWKSet.getKey (file:///app/node_modules/jose/dist/webapi/jwks/remote.js:110:13)
    at async flattenedVerify (file:///app/node_modules/jose/dist/webapi/jws/flattened/verify.js:73:15)
    at async compactVerify (file:///app/node_modules/jose/dist/webapi/jws/compact/verify.js:15:22)
    at async jwtVerify (file:///app/node_modules/jose/dist/webapi/jwt/verify.js:5:22)
    at async OIDCProvider.verifyIdToken (file:///app/dist/main.js:136786:33) {
  code: 'ERR_JWKS_INVALID'
}
```

> Alright. I also managed to solve this.
> 
> Encryption Key needs to be '---------'. Setting an Encryption Key leads to 'Invalid auth state. You might start the auth progress from another device.'
> 
> Next, you need to create a Scope Mapping in the Property Mappings in Authentik. The 'Scope Name' field is very important. Either name this email or a custom name like 'verified_email'. Put this in the Expression:
> 
> ```
> return {
>     "email": user.email,
>     "email_verified": True,
> }
> ```
> 
> In Authentik Provider for Affine, make sure this new scope is mapped and the default email scope is removed.
> 
> Now in the Affine Admin WebUI, add the new scope if you decided to use a custom name ('verified_email').
> 
> It should work now.

**Comment by seamon67** [comment]
@T00bitob Signing Key should be the Authentik one. Only Encryption Key should be null.

Edit: You also do not have claims in your Affine Web UI
{"args":{"scope":"openid verified_email profile offline_access","claim_id":"preferred_username","claim_name":"name","claim_email":"email"},"issuer":"https://\<URL\>/application/o/affine/","clientId":"\<CLI\>","clientSecret":"\<CLS\>"}

**Comment by T00bitob** [comment]
> {"args":{"scope":"openid verified_email profile offline_access","claim_id":"preferred_username","claim_name":"name","claim_email":"email"},"issuer":"https://<URL>/application/o/affine/","clientId":"<CLI>","clientSecret":"<CLS>"}

Its working now! Thank you so much @seamon67 !!!

**Comment by carlos-otero** [comment]
> [@T00bitob](https://github.com/T00bitob) Signing Key should be the Authentik one. Only Encryption Key should be null.
> 
> Edit: You also do not have claims in your Affine Web UI {"args":{"scope":"openid verified_email profile offline_access","claim_id":"preferred_username","claim_name":"name","claim_email":"email"},"issuer":"https://<URL>/application/o/affine/","clientId":"<CLI>","clientSecret":"<CLS>"}

Thank you, working fine with your help as well.

**Comment by kernelb00t** [comment]
@seamon67  Don't close this issue yet, this must be documented.

**Comment by seamon67** [comment]
> [@seamon67](https://github.com/seamon67) Don't close this issue yet, this must be documented.

It's not bug in Affine but a configuration issue with Authentik

**Comment by drandarov-io** [comment]
You can also just edit the default `authentik default OAuth Mapping: OpenID 'email'` mapping by disabling `Hide managed mappings`.

Also for me `"args":{"scope":"openid profile offline_access"}` was enough. Didn't need the other claim mapping.
