### ISSUE TITLE
[bug]: Browser APIs require a secure environment

### ISSUE THREAD

**Issue by Jones-F** [toeverything/AFFiNE#304]
### Describe the bug

Edge browser cannot SYNC DATA TO DISK

### To Reproduce

Open the demo prompts _To begin saving changes you can SYNC DATA TO DISK with the latest version of Chromium based browser like Chrome/Edge_

### Screenshots

<img width="1124" alt="image" src="https://user-images.githubusercontent.com/40933888/185781356-a024040c-41fa-4986-b882-66a9855ada38.png">
<img width="797" alt="image" src="https://user-images.githubusercontent.com/40933888/185781372-45482c1c-6c41-416d-b9bc-5b8f81174b47.png">

### Platform

Windows 11

### Browser

Microsoft Edge Version 104.0.1293.63 (Official build) (64-bit)

**Comment by alt1o** [comment]
Sorry, we could not reproduced it. Please try the lasted code in github. If you also have this problem, please reply again.

**Comment by yurening** [comment]
> Sorry, we could not reproduced it. Please try the lasted code in github. If you also have this problem, please reply again.

I also had the same problem,I deployed with the latest docker image

**Comment by yurening** [comment]
> Sorry, we could not reproduced it. Please try the lasted code in github. If you also have this problem, please reply again.

If the data cannot be stored locally this product is useless to me

**Comment by Jones-F** [comment]
> Sorry, we could not reproduced it. Please try the lasted code in github. If you also have this problem, please reply again.

Is it a limitation of local URL?

<img width="560" alt="image" src="https://user-images.githubusercontent.com/40933888/186444404-b91fb510-810c-4aba-8480-b790a8fface1.png">

**Comment by yurening** [comment]
> > Sorry, we could not reproduced it. Please try the lasted code in github. If you also have this problem, please reply again.
> 
> Is it a limitation of local URL?
> 
> <img alt="image" width="560" src="https://user-images.githubusercontent.com/40933888/186444404-b91fb510-810c-4aba-8480-b790a8fface1.png">

I have compared chrome and edge and the settings are the same. But the online demo can see the data synchronization button

**Comment by CJSS** [comment]
Would you be able to try opening the page in an incognito window (InPrivate for Edge)? Does the issue persist?

Thank you.

**Comment by yurening** [comment]
> Would you be able to try opening the page in an incognito window (InPrivate for Edge)? Does the issue persist?
> 
> Thank you.

it does not work!

**Comment by Jones-F** [comment]
> > Would you be able to try opening the page in an incognito window (InPrivate for Edge)? Does the issue persist?
> > Thank you.
> 
> it does not work!

I'm the same

**Comment by CJSS** [comment]
I'd just like to confirm you are using the latest image, you can run the following Docker command to attempt to pull the latest image - it will also let you know if you current version is also the latest.

`docker pull ghcr.io/toeverything/affine:nightly-latest`

**Comment by Jones-F** [comment]
I confirmed the cause of the problem, tested at Docker Desktop in Windows 11.

If you use http://localhost:4200/, this program works. Also include online demo.
But if you use LAN IP, like http://192.168.x.x, this program doesn't work.

The following are the results of different URLs of the same program:
**localhost**
<img width="574" alt="image" src="https://user-images.githubusercontent.com/40933888/186607741-287be653-61c7-410b-8c96-57b7d2419794.png">
<img width="563" alt="image" src="https://user-images.githubusercontent.com/40933888/186607877-416b4e8f-db16-4ee0-9f96-11f67826556b.png">

-------------------------------------------------------------
**LAN IP**
<img width="571" alt="image" src="https://user-images.githubusercontent.com/40933888/186607970-356e1b2a-d756-4e47-a6c8-847e48b6b4e6.png">
<img width="559" alt="image" src="https://user-images.githubusercontent.com/40933888/186608084-6276f304-265f-4a2b-aefb-03cd69de4aa0.png">

**Comment by CJSS** [comment]
@Jones-F Great detective work. Thanks for sharing this.

**Comment by CJSS** [comment]
You'll have no issues using this app through the localhost route - but many browser APIs are limited to secure environments.
You could try setting up a reverse proxy, or alternatively can access the online demo.

**Comment by darkskygit** [comment]
hi, we provide local storage with https://developer.mozilla.org/en-US/docs/Web/API/File_System_Access_API now, this api require only work on localhost or https site
we will add built-in tls support to the container next week and add tutorials to our documentation center. currently you can also enable the api by building an https reverse proxy outside the container

**Comment by Jones-F** [comment]
@CJSS @darkskygit Thanks for all your help.

**Comment by CJSS** [comment]
The sync to disk feature has been retired.
