### ISSUE TITLE
Self-host can not Paste images copied from other web pages.

### ISSUE THREAD

**Issue by emengweb** [toeverything/AFFiNE#6485]
### What happened?

Self-host Affine can not Paste images copied from other web pages, and download of images not work.

Judgment reason:
The following url mapping is missing:
      imageProxyUrl: '/api/worker/image-proxy',
      linkPreviewUrl: '/api/worker/link-preview',

### Distribution version

macOS x64 (Intel)

### What browsers are you seeing the problem on if you're using web version?

Chrome

### Are you self-hosting?

- [X] Yes

**Comment by pengx17** [comment]
might be a duplicate of https://github.com/toeverything/AFFiNE/issues/5944
web clipboard api is not usable without using https

**Comment by emengweb** [comment]
i think its not the same, because paste image the url route access return
homepage code. Looks like some url mapping is missing couse this happen.

Peng Xiao ***@***.***> 于 2024年4月8日周一 17:06写道：

**Comment by hch5184** [comment]
> might be a duplicate of #5944 web clipboard api is not usable without using https

i used https, it still can not work

**Comment by javix64** [comment]
> > might be a duplicate of #5944 web clipboard api is not usable without using https
> 
> i used https, it still can not work

can you explain how did you integrate https? I would like to.

**Comment by hch5184** [comment]
> > > might be a duplicate of #5944 web clipboard api is not usable without using https
> > 
> > 
> > i used https, it still can not work
> 
> can you explain how did you integrate https? I would like to.

nginx

**Comment by hch5184** [comment]
> ### What happened?
> Self-host Affine can not Paste images copied from other web pages, and download of images not work.
> 
> Judgment reason: The following url mapping is missing: imageProxyUrl: '/api/worker/image-proxy', linkPreviewUrl: '/api/worker/link-preview',
> 
> ### Distribution version
> macOS x64 (Intel)
> 
> ### What browsers are you seeing the problem on if you're using web version?
> Chrome
> 
> ### Are you self-hosting?
> * [x]  Yes
> 
> ### Relevant log output
> _No response_
> 
> ### Anything else?
> _No response_

i found the repository
https://github.com/toeverything/affine-workers

but can only deploy in Cloudflare 

you can make wheel by yourself in other programming languages

**Comment by matheusriios** [comment]
Some updates about that? I'm having the same issue.

https://discordapp.com/channels/959027316334407691/1231935115303718953

**Comment by pengx17** [comment]
I see. Sorry about the statement I made about https. It clearly related to the image-proxy issue.
It looks like we haven't including workers in the self-host version. Before we do, you need to either deploy https://github.com/toeverything/affine-workers onto a cloud service like Cloudflare, or adopt the code to make it running on your server somehow, which should not be too difficult.

**Comment by eikaramba** [comment]
i tried to deploy the cloudflare worker but there were too many obstacles along the way. i have rewritten the worker now as a simple express app which can be deployed locally via docker. i only tried out the link-preview endpoint (is the image proxy used anywhere else apart from within the link preview endpoint?) and it works flawlessly now.
https://github.com/eikaramba/affine-workers

**Comment by emengweb** [comment]
> 我尝试部署 cloudflare worker，但一路上遇到了太多障碍。我现在已经将 worker 重写为一个简单的 express 应用程序，可以通过 docker 在本地部署。我只尝试了 link-preview 端点（除了在 link preview 端点内，图像代理是否在其他地方使用？）现在它运行完美。https [://github.com/eikaramba/affine-workers](https://github.com/eikaramba/affine-workers)

it worked!

**Comment by picolino** [comment]
@eikaramba how did you change default base url for image-proxy?
My self hosted affine still trying to call app.affine.pro instead of my hosting domain, but other urls works properly.

**Comment by eikaramba** [comment]
@picolino i didn't needed to change anything in my self hosted affine. it was by default calling the local endpoint, resp. trying to.
e.g. https://my.local.affine.domain/api/worker/link-preview

then i added a manual redirect in nginx to let this redirect to the docker container running this worker and voila, it worked.

are you sure it is trying to connect to app.affine.pro ? add a youtube link and then click on the link and switch to card view instead inline and observe with the browser tools in the network tab what is going on then.

i'm on latest affine as of today:
0.15.7
editor 0.16.0-canary-202407200848-42035fe

**Comment by eikaramba** [comment]
i now see you are talking about the image-proxy. i honestly haven't tried this out and frankly i don't know how. how do you test this?

**Comment by picolino** [comment]
@eikaramba 

To test this just press Reload on link block
![image](https://github.com/user-attachments/assets/78426802-1a37-48fd-9aa0-09a8f7f4ce65)

It is ok for link-preview, it is my host:
![image](https://github.com/user-attachments/assets/f352607a-610a-48f6-adbd-7b03b0498ab4)

But not for image-preview:
![image](https://github.com/user-attachments/assets/bd55ba7d-9d6d-4a46-ac83-0b97d4f8a6be)

As you can see - no images on link block persists.

I don't understand why is this happening...

**Comment by eikaramba** [comment]
strange i tested to embed https://github.com/toeverything/AFFiNE as a link

![grafik](https://github.com/user-attachments/assets/b48c4454-0c05-42f3-aa9f-fd1dfd66764f)

works fine. it has to be because of what the link-preview is returning for you. 

Did you set the host name in the docker environment correctly?
```
services:
  worker:
    build: .
    expose:
      - 9930
    ports:
      - 9930:3000
    environment:
      - HOST_NAMES=${HOST_NAMES}
networks: {}
```
where HOST_NAMES is a variable i have set. e.g. HOST_NAMES=https://my.affine.instance

**Comment by picolino** [comment]
@eikaramba Nah, I used app.affine.pro workers, because of that these workers gave me back that url.

I deployed your affine workers in docker - everything is fine.

Just to mention, if you gonna use it too:

1. Change HOST_NAMES env in compose.yaml to: HOST_NAMES=https://\<your hostname\>
2. Change `src/utils/headers.ts`, add your host to allowed origins.

Also, you could inject workers compose.yaml in basic affine compose to launch both in one command:

```yaml
services:
  workers:
    container_name: affine_workers
    extends:
      file: ../affine-workers/compose.yaml
      service: worker
```

**Comment by YummYume** [comment]
Hey, just wanted to share a Docker image I made in the meantime for self-hosted instances running on Docker : https://github.com/YummYume/affine-bun-workers

Heavily inspired by @eikaramba, thanks a lot ! It supports image proxying and link preview.

**Comment by eikaramba** [comment]
nice @YummYume - i have set it up along with my docker workers instance. however with the exact same config i get:
```
affine_workers  | {"level":30,"time":1730926457377,"pid":1,"hostname":"ecde50e90b96","request":{"method":"POST","url":"http://xxxxxxxx/link-preview","referrer":"https://xxxxxxxxx/workspace/0200a9ce-ff65-421d-9f4e-d498c9a7cb23/8rgvShdQVlqnTWTMCIGMY"},"code":"NOT_FOUND","message":"NOT_FOUND"}
```

i am trying to fetch the meta data from this link:
https://www.youtube.com/watch?v=Twn_4AW0M6U

maybe it is just some silly error on my side, i am not so keen into the frameworks you are using. i just thought that with the same config it should run immediately.

**Comment by YummYume** [comment]
Hey @eikaramba ! I just tested on my end and it works :

![image](https://github.com/user-attachments/assets/b0d3841c-7c96-4ebe-bb9e-a6906acc4847)

Since you're getting a not found, it's probably an issue with the prefix `/api/worker`, is your reverse proxy stripping it from the path before sending it to the worker ? In that case, you need to set the `ELYSIA_PREFIX` variable on the service to an empty string (by default it expects `/api/worker` as a prefix).

**Comment by eikaramba** [comment]
unfortunately it is still not working, tried all different combinations. always the same error. but nevermind, i will just continue using my repo.

**Comment by YummYume** [comment]
@eikaramba Fair! I'm sorry it didn't work as intended for you, I'd be glad to help anyone that needs help with this in the future
